### ISSUE TITLE
TODO: Features and bugs

### ISSUE THREAD

**Issue by rubiin** [rubiin/asdfui#1]
- [x] clear screen on launch
- [x] show some msg for no versions installed
- [x] install selected versions
- [x] uninstall selected version
- [ ] mark installed versions with installed
- [x] set selected version as global
- [x] add cancellable promises
- [ ]  add cache
